### ISSUE TITLE
Is rapidfuzz vecotrized

### ISSUE THREAD

**Issue by TheBubblePopped** [rapidfuzz/RapidFuzz#103]

**Comment by maxbachmann** [comment]
The Implementations for the Levenshtein distance and the InDel distance (similar to Levenshtein but Substitutions do not exist) use a bitparallel implementation, which calculates the distance for 64 characters at once. All of the scorers in the fuzz module use the InDel distance in the end, but perform additional operations (e.g. to sort the words), which so far are not vectorized (I am not aware of any faster vectorized implementations for these operations, so suggestions/implementations are welcome).

It would be possible to improve the performance for string lengths above 64 characters by using wider vectors like e.g. 128 bit. However this would require runtime dispatching of the appropriate implementation, so the library still works on platforms which do not support those operations. Probably the biggest effort would be the runtime dispatching, since the implementation already uses vectors anyways (see e.g. [here](https://github.com/maxbachmann/rapidfuzz-cpp/blob/4ce9fe741bbe48e5f791bc4ab828098081ad4f5c/rapidfuzz/details/string_metrics/weighted_levenshtein_impl.hpp#L128)), so using wider vectors should be fairly straight forward.
