### ISSUE TITLE
Passing a numpy array instead of python list to rapidfuzz.process.extract increases runtime by *4+

### ISSUE THREAD

**Issue by TheBubblePopped** [rapidfuzz/RapidFuzz#104]
I was trying to preprocess my numpy string by myself in the numpy array and passing that to the extract function. My data was stored in numyp anyway, does that mean i will have to first reconvert the thing to a list?

**Comment by maxbachmann** [comment]
## Explanation
Currently there is no specialized code for numpy arrays. So they are treated in a similar way to a list:
```python
for item in list:
   calculate_similarity
```
Since the similarity calculation in RapidFuzz is super fast it becomes relevant how long it takes to get elements out of this list. In fact I was thinking about changing the return value of process.extract to a numpy array in the future, since the creation of the result list will be by far the slowest part of the function when all results are requested (`limit=None`).

I wrote a quick test of the performance of numpy arrays and a python list when iterating:
```python
from timeit import timeit

print(timeit(
"""
[b for b in a]
""",
setup="""
import numpy as np
a = np.array(["aaaaaaaaaaaaa"]*100000)
""", number=100
))

print(timeit(
"""
[b for b in a]
""",
setup="""
a = ["aaaaaaaaaaaaa"]*100000
""", number=100
))
```
On my machine the numpy solution takes about 20 times as long as the list based version:
```
2.6755985069903545
0.16193171300983522
```
This is probably because numpy stores the strings in a optimized fashion and has to create string objects while iterating. So I do not think that you will get any performance improvements by converting the numpy array to a list before you call the function.


## Solution
The proper solution would be to write a specialized implementation for numpy arrays, which directly accessed the elements through the Numpy C Api. Afterwards it should be as fast (if not faster) than the implementation for lists. I think I should be able to implement this for one of the next versions.

**Comment by TheBubblePopped** [comment]
"This is probably because numpy..."
Yep, exactly. 

".So I do not think that you will get any performance improvements by converting the numpy array to a list before you call the function."
Did you mean, i will not get an important performance increase by converting a list in a numpy array instead?

"The proper solution would be to write a specialized implementation for numpy arrays"
This would be legendary and could yield good results. Ironically passing a series with it's index is faster than passing a numpy array.
While a series needs 2*list_execution_time with the normal ratio scorer the difference of using partial_ratio is only +30% (list vs series)

Lastly:
Are you related to Erlich Bachman?

**Comment by maxbachmann** [comment]
> Did you mean, i will not get an important performance increase by converting a list in a numpy array instead?

Yes I would expect it to perform slightly worse, since it still has to perform the same operations to convert it to a list. Afterwards there is still some overhead to get them from the list again.

> Ironically passing a series with it's index is faster than passing a numpy array.

This behaves in a different way. a pandas series is handled similar to a dictionary by iterating over `series.items`. I think inside a pandas series strings are stores as a Python object (any length of strings), while numpy stores them in an optimized way (e.g. dtype='<U13'). So numpy has to create Python string objects, while pandas can just return them.

> This would be legendary and could yield good results.

Yes I directly use the buffer inside strings anyways, so in a similar way a solution using the Numpy C Api could directly read the internal buffer of the numpy arrays

> Are you related to Erlich Bachman?

From a quick google search it appears that he is a character from the show Silicon Valley, which I never watched ;)
So I guess no I am not.

**Comment by TheBubblePopped** [comment]
There is a chance that you get faster results by using .apply() to iterate over the pandas series.
You should watch it(Silicon Valley), it's hilarious and Erlich Bachman is a very good actor, in a way that makes me question if he is acting at all. 

Anyway, closing this ticket. Wish u a great week!
