### ISSUE TITLE
Type library

### ISSUE THREAD

**Issue by Phxntxm** [rapidfuzz/RapidFuzz#109]
Lately python has been obsessed (and rightly so IMO) with statically typing libraries for ease of use by developers wanting to use the library. This is obviously not a required thing by any means, but a very nice QOL feature to have. If this wasn't written in cpp I'd offer to do a PR for it... but... I don't know jack about cpp and I'm not interested in looking through it to figure it out. 

I would just like to offer the suggestion of typing rapidfuzz up, providing [type stub files ](https://mypy.readthedocs.io/en/stable/stubs.html) for tools like Mypy and Pyright to help type check against

**Comment by maxbachmann** [comment]
> If this wasn't written in cpp I'd offer to do a PR for it... but... I don't know jack about cpp and I'm not interested in looking through it to figure it out.

For the typing you can simply check the cython files (*.pyx). 
rapidfuzz.fuzz: https://github.com/maxbachmann/RapidFuzz/blob/main/src/cpp_fuzz.pyx
rapidfuzz.string_metric: https://github.com/maxbachmann/RapidFuzz/blob/main/src/cpp_string_metric.pyx
rapidfuzz.process: https://github.com/maxbachmann/RapidFuzz/blob/main/src/cpp_process.pyx
rapidfuzz.utils: https://github.com/maxbachmann/RapidFuzz/blob/main/src/cpp_utils.pyx

They should be simple to understand even without any knowledge in cython/C++. Since most functions have the same interface (e.g. most scorers share a similar interface) the typing should be fairly simple.

> Lately python has been obsessed (and rightly so IMO) with statically typing libraries for ease of use by developers wanting to use the library.
> I would just like to offer the suggestion of typing rapidfuzz up, providing type stub files for tools like Mypy and Pyright to help type check against

I would love type stub files :)

**Comment by Phxntxm** [comment]
Well hey those don't look bad at all! I will probably work on some, I should have looked before just giving up lmao. Thanks!

**Comment by maxbachmann** [comment]
Note that the interface becomes a bit more generic in the next release. The library does now accept `Iterable[Hashable]` instead of `str`. As an example:
```python
float ratio(
  s1: str,
  s2: str,
  processor: Union[bool, None, Callable] = None,
  score_cutoff: Union[float, None] = None) 
```
changes to
```python
float ratio(
  s1: Iterable[Hashable],
  s2: Iterable[Hashable],
  processor: Union[bool, None, Callable] = None,
  score_cutoff: Union[float, None] = 0) 
```

**Comment by Phxntxm** [comment]
Alright, there's two issues I can see with properly typing the `scorer` callable inside of `process.extract*`.

- It passes through `**kwargs` but NOT `*args`
  -  There is `ParamSpec` which can only be used if both are used... but cannot be used if only one is used. To properly type this it would require passing through `*args, **kwargs` which would include changes to the lib. Is this desirable? It seems like that should be fine to me... but the next point
- To properly type param spec ALONG WITH other parameters passed as well would require `Concatenate` which is not part of the library `typing`, it's a part of typing-extensions which would require including that as a dependency. Is that desirable as well?


It could just be lazily typed as `scorer: Callable, **kwargs: Any` if these aren't desirable however

**Comment by maxbachmann** [comment]
> There is ParamSpec which can only be used if both are used... but cannot be used if only one is used. To properly type this it would require passing through *args, **kwargs which would include changes to the lib. Is this desirable? It seems like that should be fine to me... but the next point

I would prefer using only kwargs, since usually not all parameters are defined and `scorer` is passed as named argument. So it would become a bit confusing when the args are passed and when they are interpreted as one of the other parameters. A similar API is available e.g. in scipy:
```python
scipy.spatial.distance.cdist(XA, XB, metric='euclidean', *, out=None, **kwargs)
```
which passes the `**kwargs` to the metric as well.

> To properly type param spec ALONG WITH other parameters passed as well would require Concatenate which is not part of the library typing, it's a part of typing-extensions which would require including that as a dependency. Is that desirable as well?

It would be fine to add `typing-extensions` as a dependency.

> It could just be lazily typed as scorer: Callable, **kwargs: Any if these aren't desirable however

In case there is no other way, I think this is good enough.

**Comment by Phxntxm** [comment]
So this does become a bit difficult because `ParamSpec` is a little.... underwhelming. It does require both args and kwargs to be used, otherwise it errors. So if args isn't desirable (which thinking about it a bit more, I don't disagree with. Especially since with more limitations of `ParamSpec` args would be required to come AFTER the callable it's used in, which means `args` would have to go after the keyword arguments lol.

With that in mind I think the lazy typing for that callable is the best that can be done, I'll work forward on that idea :+1:

**Comment by Phxntxm** [comment]
Addressed in https://github.com/maxbachmann/RapidFuzz/commit/61a7eeaaf20fb4a1bae3e904563756795b0a434b
