### ISSUE TITLE
Partial Ratio Giving Unexpected Result

### ISSUE THREAD

**Issue by Hillard28** [rapidfuzz/RapidFuzz#147]
In the case of matching via partial_ratio between the following strings:
"GREAT GREEK 70005"
"GREAT GREEK MEDITERRANEAN GRILL WINTER GARDEN"

A partial score of 71% is expected, but RapidFuzz returns 82.8%.  Is this an intended result?  The return from FuzzyWuzzy is 71% as well.

**Comment by Hillard28** [comment]
This appears to affect other processes as well.  The ratio command used on the following:
"ADAMS & O REILLY"
"HAND & STONE"

returns a score of 50%

**Comment by maxbachmann** [comment]
The `fuzz.partial_ratio` implementation used in RapidFuzz has a couple of differences from the implementation used by FuzzyWuzzy.
1) FuzzyWuzzy searches for the substring in the longer string, which has the highest `fuzz.ratio`. This substring has to be of len(shorter), but can be shorter when it is placed at the end of the longer string. So the following alignments are valid:
```
abcd<->abcd
abcd<->bcd
abcd<->cd
abcd<->d
```
However, the following are not:
```
abcd<->abc
abcd<->ab
abcd<->a
```

This means that `fuzz.partial_ratio(a, b)` can lead to different results than `fuzz.partial_ratio(b, a)`:
```python
>>> fuzz.partial_ratio("aba", "aab")
80
>>> fuzz.partial_ratio("aab", "aba")
67
```
since the alignment `aba <-> ab` is valid for the first calculation, but the alignment `aab <-> ab` for the second string is not.

2) To improve the performance FuzzyWuzzy searches for the longest common substrings and uses them as starting points for the calculation of the `fuzz.ratio`:
```python
for block in SequenceMatcher(None, shorter, longer).get_matching_blocks():
    long_start = block[1] - block[0] if (block[1] - block[0]) > 0 else 0
    long_end = long_start + len(shorter)
    long_substr = longer[long_start:long_end]
        
    fuzz.ratio(shorter, long_substr)
```
This works kind of well, but does not always find the optimal alignment. 

3) it uses either difflib or when installed python-Levenshtein (python-Levenshtein has a broken implementation of get_matching_blocks)


In RapidFuzz I changed this behavior for short strings (shorter string <= 64), while I use the same implementation for long strings (shorter string > 64). In my implementation, I allow shorter substrings at both ends of the longer string. So `fuzz.partial_ratio(a, b) == fuzz.partial_ratio(b, a)`. In addition, I test all alignments and not only alignments, starting at one of the longest common substrings. This means the implementation always finds the substring with the highest `fuzz.ratio`.

For long strings the calculation of `fuzz.ratio` becomes significantly slower, so I fall back to the implementation used by FuzzyWuzzy in these cases.

Here is how this applies to your example:
```
"GREAT GREEK 70005"
"GREAT GREEK MEDITERRANEAN GRILL WINTER GARDEN"
```
Here FuzzyWuzzy find the optimal alignment
```
"GREAT GREEK 70005"
"GREAT GREEK MEDI"
```
While RapidFuzz finds the optimal alignment
```
"GREAT GREEK 70005"
"GREAT GREEK "
```
which has a higher similarity, but is an invalid alignment in FuzzyWuzzy.

In your second example, both FuzzyWuzzy and RapidFuzz return the same result, since they use the same alignment:
```
"ADAMS & O RE"
"HAND & STONE"
```

**Comment by Hillard28** [comment]
Got it, thank you!  The results in the first case make sense, I guess I'm still a bit confused about the second case.  I saw both implementations result in a score of 50%, but I'm at a bit of a loss as to why.  Is there a lower penalty because the algorithm is shifting " " and "&" in the comparison?  Is there anyway to force equal weighting of insertion, deletion, etc?

**Comment by maxbachmann** [comment]
When using `fuzz.partial_ratio` both implementations should return 58:
```python
>>> fuzz.partial_ratio("HAND & STONE", "ADAMS & O REILLY")
58.333333333333336
```

However, I assume you are asking about the result of `fuzz.ratio`?
```python
>>> fuzz.ratio("HAND & STONE", "ADAMS & O REILLY")
50.0
```

fuzz.ratio uses the normalized InDel distance, which behaves like the Levenshtein distance except that it does not allow substitutions (substitutions are a insertion + deletion). This behavior can be achieved e.g. by using the Normalized Levenshtein distance with a weight of 2 for substitutions:
```python
>>> string_metric.normalized_levenshtein("HAND & STONE", "ADAMS & O REILLY")
25.0
>>> string_metric.normalized_levenshtein("HAND & STONE", "ADAMS & O REILLY", weights=(1,1,2))
50.0
```
A different similarity metric, which is often used to compare names, is the jaro winkler similarity:
```python
>>> string_metric.jaro_winkler_similarity("HAND & STONE", "ADAMS & O REILLY")
63.888888888888886
```

**Comment by Hillard28** [comment]
Thanks for this and sorry for wasting your time!  Looks like my confusion stemmed from trying to compare the results with the output of a bigram-Jaccard process.  Love the module, now just need to figure out how to best incorporate with this study!

**Comment by maxbachmann** [comment]
No problem. Glad I could help :)
