### ISSUE TITLE
Different scores between fuzzywuzzy and rapidfuzz

### ISSUE THREAD

**Issue by DaanMocking** [rapidfuzz/RapidFuzz#30]
Based on this [Stackoverflow message](https://stackoverflow.com/a/61102196), I expected rapidfuzz and fuzzywuzzy to return identical scores (apart from rapidfuzz providing a higher precision). However, I notice different results in certain situations. For an example, see the code below.

Are my expectations incorrect and is this difference in behavior as expected?

```
from fuzzywuzzy import fuzz as fuzzy_fuzz
from rapidfuzz import fuzz as rapid_fuzz  # 0.7.10

string_1 = "abc defgh"
string_2 = "gelieve deze nota binnen 14 dagen te voldoen op iban tnv abcdefgh"

fuzzy_fuzz.partial_ratio(string_1, string_2)  # -> 89
rapid_fuzz.partial_ratio(string_1, string_2)  # -> 94.11764705882352
```

**Comment by maxbachmann** [comment]
Yes they are supposed to return the same results, but the case your mentioning here is an exception. partial_ratio is supposed to return the best possible string alignment between the shorter and the longer string. The best alignment that rapidfuzz is using in your example is
```
"abc defgh"
"abcdefgh"
```
This requires only one delete -> the score is 94.11764705882352 (rapidfuzz does not round the result since people might want to keep the precision, so in fuzzywuzzy this would return 94)

FuzzyWuzzy on the other hand uses the following alignment
```
"abc defgh" 
 " abcdefgh"
```
This requires one delete of a whitespace and to insert one whitespace which therefore returns a score of 89

This is caused by fuzzywuzzy using python-Levenshtein to find the best string alignment since it is faster than difflib. While this is true I can not simply use their algorithm of this, simply because it is GPL Licensed and I have never seen this algorithm under a more permissive license (since I basically know what they do since I read the code of python-Levenshtein I am not able to implement this myself, since it would definetly result in a deriver work, while I want to use the MIT License). In general both with difflib and python-Levenshtein the best string alignment should be the same. However there is a bug in python-Levenshtein: https://github.com/ztane/python-Levenshtein/issues/16 (apparently it is known how to fix it). So in your example the results are different, because fuzzywuzzy does not find the correct best string alignment using python-Levenshtein

I hope this clears up the confusion :)

**Comment by DaanMocking** [comment]
Thank you for your quick and elaborate response! I did not know about this bug in python-Levenshtein. I defintely understand the licensing considerations, it is one of the reasons we are investigating replacing fuzzywuzzy with rapidfuzz.

So, if I understand correctly, rapidfuzz' behavior in this situation is desired (and even an improvement) compared to fuzzywuzzy?

**Comment by maxbachmann** [comment]
Yes it is. You can see the desired output with fuzzywuzzy when using it with difflib:
```
from fuzzywuzzy import fuzz as fuzzy_fuzz
from difflib import SequenceMatcher

string_1 = "abc defgh"
string_2 = "gelieve deze nota binnen 14 dagen te voldoen op iban tnv abcdefgh"

fuzzy_fuzz.SequenceMatcher = SequenceMatcher
fuzzy_fuzz.partial_ratio(string_1, string_2)  # -> 94
```

**Comment by DaanMocking** [comment]
Great, thanks!

**Comment by cktang88** [comment]
Hey @maxbachmann, should I expect the get the same output for fuzzywuzzy and RapidFuzz if I set `fuzzy_fuzz.SequenceMatcher = SequenceMatcher`? currently I'm getting different results for a wide variety of strings even after setting that, would love any insight you could give here!

versions:
```
fuzzywuzzy==0.17.0
rapidfuzz==1.4.1
```

Script to test:
```python
>>> from fuzzywuzzy import fuzz
>>> from difflib import SequenceMatcher
>>> fuzz.SequenceMatcher = SequenceMatcher
>>>
>>> from rapidfuzz import fuzz as fuzz2
>>> import string, random
>>> def randomString(N):
...     return ''.join(random.choice(string.ascii_lowercase + ' ') for i in range(N))
...
>>> for i in range(100):
...     n1, n2 = random.randint(5, 30), random.randint(5, 30)
...     a,b = randomString(n1), randomString(n2)
...     s1, s2 = fuzz2.partial_ratio(a,b), fuzz.partial_ratio(a,b)
...     if round(s1) != s2:
...         print([a, b], 'fuzzywuzzy=', s2, ', rapidfuzz=', s1)
...
['wopkecbznnanzifd', 'npzuysdahdug dmziowkqef'] fuzzywuzzy= 25 , rapidfuzz= 25.80645161290323
['uzoulzx ltmhgpousnrpyqrtgj', 'wucruhzjdete'] fuzzywuzzy= 26 , rapidfuzz= 33.33333333333333
['mrixnmzqkgbplrrbenropyrjjkj', 'dobdeiljeifykkftgddbxcjad'] fuzzywuzzy= 24 , rapidfuzz= 25.641025641025635
['rvgf cb mydhs', ' yblicilbcu'] fuzzywuzzy= 20 , rapidfuzz= 30.0
['mcamxfzzc shypxxzxizorkm', 'pxbriujaillwpnpimnosynnyoeaoq'] fuzzywuzzy= 17 , rapidfuzz= 20.83333333333333
['u jdpzwgglgmfzcrsq', ' sbmlbyxnejkfvasopefqfniipku'] fuzzywuzzy= 11 , rapidfuzz= 22.22222222222223
[' klnmyfvtdsbfvjve', 'tkrmnccxpr moj'] fuzzywuzzy= 17 , rapidfuzz= 28.57142857142857
['vosephklgnoqlhkvpjnifrid', 'rekgeqzuhqsyhtgrzgtksxhhftm'] fuzzywuzzy= 24 , rapidfuzz= 25.531914893617028
['ewfikmaakbnjpblgacqt', 'tlnuqkfwym hwg'] fuzzywuzzy= 13 , rapidfuzz= 14.285714285714292
['aemugioqwg tjxpa ibpa', 'irilvthcj ydkbqpm'] fuzzywuzzy= 26 , rapidfuzz= 36.36363636363637
['yvqgczpbmmrdwfnutghs ', 'tknwyxlvhb jlcftwichmmxpjkn'] fuzzywuzzy= 24 , rapidfuzz= 28.57142857142857
['xxvykynuyftocarxvqp seapi', 'bgsaoatqllggewnbukodw'] fuzzywuzzy= 15 , rapidfuzz= 19.04761904761905
['cupjolpoeomkbmgqmm ', 'rnuqhjptffzofyjd'] fuzzywuzzy= 12 , rapidfuzz= 25.0
['aaqujkfpor mlk', 'bcvmiyzpgmgyrqpskc'] fuzzywuzzy= 19 , rapidfuzz= 28.57142857142857
['jsxzchwnxi jjhwzhuisz', 'bpsp ccjnufbmkmgzf'] fuzzywuzzy= 22 , rapidfuzz= 25.80645161290323
['nnekkttbvfhut aldphslgwvwmyk', 'nxfvop iigehqgfq'] fuzzywuzzy= 19 , rapidfuzz= 25.0
['bsjxzwqinjoidehdszkd', 'lepejfmowrlmamwiureajioumgs'] fuzzywuzzy= 9 , rapidfuzz= 25.0
['orvfhjygghseaad', 'ajtmeigyeyxdkqjv '] fuzzywuzzy= 11 , rapidfuzz= 20.0
['tctmvcdmkuqtg pwmxaalzlcvfb', 'ls loswlampyozkrfu sbak'] fuzzywuzzy= 27 , rapidfuzz= 29.268292682926827
['bwjelhpbcrhudwtamvdki', 'p oprzwkpcprvvkx'] fuzzywuzzy= 26 , rapidfuzz= 32.25806451612904
['kgfliqm ptjtpvylvcn', 'wcoeafokqcpxpihdneigc'] fuzzywuzzy= 18 , rapidfuzz= 30.303030303030297
['eipxrxwajdamlvywqdkymdgoh', 'scrkazausukvextcrqfwol'] fuzzywuzzy= 14 , rapidfuzz= 27.272727272727266
['bnoncpyonfibx ljeuxxcsic', 'spynzerqytqmeenyznjpnlxgkyqxd'] fuzzywuzzy= 23 , rapidfuzz= 32.55813953488372
['an ulhcsj', 'xfnubdjp tzx'] fuzzywuzzy= 22 , rapidfuzz= 33.33333333333333
```

**Comment by maxbachmann** [comment]
Hey @cktang88. No even in this case they will not have the same results for multiple reasons I will explain below. Since this difference between the two implementations leads to a lot of confusion it should probably be explained somewhere in the documentation of RapidFuzz as well. I am not sure when I will find the time for this (PRs are always welcome :wink: )

There are the following differences:
1) I never use the automatic junk heuristics of difflib, while fuzzywuzzy does not disable them (probably because this was not possible when fuzzywuzzy was developed for Python2.7) see https://github.com/seatgeek/fuzzywuzzy/pull/303. However this is only relevant for very long strings.
2) While I use the get_matching_blocks implementation from difflib I calculate the similarity using the Levenshtein distance similar to python-Levenshtein.

You can reproduce the same results in FuzzyWuzzy in the following way:
```python
import Levenshtein
from difflib import SequenceMatcher

class StringMatcher:
    def __init__(self, isjunk=None, seq1='', seq2=''):
        self._str1, self._str2 = seq1, seq2

    def get_matching_blocks(self):
        return SequenceMatcher(None, self._str1, self._str2, False).get_matching_blocks()

    def ratio(self):
        return Levenshtein.ratio(self._str1, self._str2)

from fuzzywuzzy import fuzz
fuzz.SequenceMatcher = StringMatcher
```
