### ISSUE TITLE
ImportError: DLL load failed while importing _process: The specified module could not be found.

### ISSUE THREAD

**Issue by mettlemind** [rapidfuzz/RapidFuzz#42]
Hello Max,

Greetings for the day!

While I was trying to import process and utils module from rapidfuzz, I have encountered with the below error.
ImportError: DLL load failed while importing _process: The specified module could not be found.

I have C++ 2019 redistributable  installed on my laptop.
I also can see the process.py in my anaconda package folder.

I have installed both "0.11.1" and "0.10.0" versions but no luck in both cases.

Please help me in fixing this issue, Thanking you!

**Comment by maxbachmann** [comment]
Hm thats strange, since process is implemented in python, so there is no _process, that should be imported :confused: 
(For me it works fine on Windows)

_process did exist until something around version 0.7/0.8 (I do not remember when exactly it was removed), so when working with a new version this should not occur. Are you really sure your actually using these version? (I guess I should add a \_\_version\_\_ for future versions ...)

**Comment by mettlemind** [comment]
<img width="618" alt="Capture" src="https://user-images.githubusercontent.com/63039755/92987454-1a574500-f4e0-11ea-8b9b-8676d0df45e5.PNG">

Hello Max, 
I have attached the snip of my error for your reference, please have a look
I tried in 2/3 different machines, same error pops up

**Comment by maxbachmann** [comment]
I could not reproduce this myself. For me this error only occurs when the C++ redistributable is missing.
Does this error occur with other modules that are using C/C++ aswell (e.g. python-Levenshtein)?

**Comment by maxbachmann** [comment]
closed because the error could not be reproduced and there was no update from the the issue creator.
