### ISSUE TITLE
suggestion: many to many match

### ISSUE THREAD

**Issue by its-grape-juice** [rapidfuzz/RapidFuzz#51]
Great project,
Is there a possibility of optimization when matching a list of queries against a list of choices?

**Comment by maxbachmann** [comment]
There are ways to optimise when working with lists, so e.g. some preprocessing is only done once. So far I only provide `process.extract` and `process.extractOne` to match one element against a list (they already use some of these improvements).
I guess we could add functions to match two lists against each other in a similar way, which return either a result matrix or list.

**Comment by jleem-iso** [comment]
Yes please! Though, would `scipy`'s `cdist` or `pdist` be efficient enough?

**Comment by maxbachmann** [comment]
@ideasbyjin thanks for pointing out the similar api of scipy. I did not work with scipy yet, but the api of cdist seems pretty similar to what we would need here aswell

The current idea of the implementation is something like this:
```python
# this sets how many elements are allowed to be preprocessed at any time
# used so memory consumption does not become to big
max_proc_len = ...

if max_proc_len <= len(shorter_list):
    # len(shorter_list) + len(longer_list) times preprocessed
    for string in shorter_list:
        proc_shorter_list.append(preprocess(string))

    for string1 in longer_list:
        string1 = preprocess(string1)
        for string2 in proc_shorter_list:
            ratio(string1, string2)
else:
    # len(shorter_list) * len(longer_list) / max_proc_len times preprocessed
    cur_index = 0
    for segment_index in range(len(longer_list) // max_proc_len):
        cur_index = segment_index * max_proc_len
        proc_segment_list = [
            preprocess(longer_list[cur_index + index])
            for index in range(max_proc_len)
        ]
        for string1 in shorter_list:
            string1 = preprocess(string1)
            for string2 in proc_segment_list:
                ratio(string1, string2)

    cur_index += max_proc_len
    if len(longer_list) - cur_index:
        proc_segment_list = [
            preprocess(longer_list[cur_index + index])
            for index in range(len(longer_list) - cur_index)
        ]
        for string1 in shorter_list:
            string1 = preprocess(string1)
            for string2 in proc_segment_list:
                ratio(string1, string2)
```

The goal of this is to avoid preprocessing strings when possible. However it preprocesses strings multiple times when otherwise the memory consumption would be become to big. Preprocessing consists out of two components:
1) the processor passed to the function (in case of the default_processor this lowercases and replaces non alphanumeric characters)
2) preprocess parts of the scorer, that have to be calculated multiple times. E.g. when `fuzz.token_sort_ratio` is used this sorts the words in the string only once in this preprocessing step and then uses `fuzz.ratio` instead of `fuzz.token_sort_ratio` afterwards (this can only be done for scorers that are implemented by RapidFuzz and not for scorers implemented by the user)

**Comment by zeek-ja** [comment]
Any advances on this? i have a list of 57 thousand titles to match against 498,538 titles in our database... long story short, this would be an absolute killer addition.

**Comment by maxbachmann** [comment]
I started to work on a `cdist` addition yesterday, which would take two lists and return a numpy matrix with the similarity between all elements.

Btw some things I am looking for input:
1) did you test the current performance of the library? I am especially interested in the performance difference between the normal installation `pip install rapidfuzz` and a source installation `pip install  --no-binary :all:`. On my machine many of the similarity calculations in the source version are about twice as fast (probably due to some CPU specific optimizations the compiler chooses). So it would be interesting to know whether other people experience the same, since then I should probably mention it in the documentation.

2) What are the average string lengths your working with (<=8, <=16, <=32, <=64, >64).

**Comment by zeek-ja** [comment]
Hi Max, I have tested and continue to test RapidFuzz in an app (search engine really) I developed to search and match titles for a few corp. apps in an environment where dealing with titles is the business. I've run a couple of tests comparing RF to FW and there is a notable difference in processing time. Typically the runs using the RF matcher will return within 20ms averaging around 17ms with the very longest being  93ms (this includes all the layers that come before it) whereas with FW we see anywhere from 150 to 300ms response times. It's pretty significant as we run playlist matches that are usually in the tens of thousands of track titles against a huge repertoire, approaching half a million titles with all kinds of versions, contributors, etc etc. Hence the interest in many-to-many matching.

I'd just like to add that this tool affects performance in an impactful way so, thanks for the great implementation.

p.s. I forgot to mention that i've only tested calling the scorers directly, i have yet to test process.

**Comment by maxbachmann** [comment]
Process has two advantages:
1) it does not has to switch between Python/C++ a lot of times, so a lot of conversions between the Python and C++ types are not required (function calls in Python are super expensive, since they build a list and dict for the args/kwargs each time and then parse it to store the elements into the variables)
2) I save some time on the scorers that are used. E.g. the bitparallel Levenshtein implementation I use requires a conversion of one of the two strings to bitvectors. I can do this once for the query and then reuse them for all comparisions. Similar for token_sort_ratio, where I only have to sort the words in the query once.
So using process.extract should be a lot faster especially for fuzz.ratio.

The process.extractOne benchmark I show in the Readme allows extractOne to exit on average after 50% of the elements, since it found a perfect match. So process.extract should have about half of the throughput, which is still a 2x-5x improvement over the direct usage of the scorers. And in general when matching the same dataset multiple times and your using a preprocessing function (activated by default in many scorers and process, but can be deactivated using `processor=None`), try to do the preprocessing ahead of time. The speed impact is shown in fuzz.ratio vs fuzz.QRatio. fuzz.ratio does not preprocess by default, while fuzz.QRatio does.

**Comment by zeek-ja** [comment]
I'll definitely take that into account as i design the next set of tests. I may work on it over the weekend and let you know how it works out.

btw, i used token_sort and token_set ratios exclusively in my previous tests, do you recommend i just use ratio or some other variation to improve performance?

basically, I have three things that i need to take into account when running a match, the title, the artist, and the version. I use the token_sort on the titles as they're often misspellings, etc,  for artist and version I've been playing around with the token sort and set ratios and even going as far as running both and taking the average for a somewhat weighted score. Bare in mind that it's my first go at this and find myself just trying everything out and seeing what gives the best results/performance.

EDITED: I re-read the docs and answered most of my questions. Will let you know how it goes.

**Comment by zeek-ja** [comment]
I've completed my initial tests and have come to a couple of conclusions;
1. The process method over the fuzz method (iterating over large datasets row-wise) is much faster as there's no requirement to iterate which adds loads of overhead, pretty obvious with noted increases in speed on a per match basis but not applicable in my use case.
2. I'm forced to use the fuzz method as i need more granularity than the process methods afford at this point. A many to many match with weights for each feature would be needed for this case.
In an effort to explain:

I have to match recordings with registered tracks in a db. Each recording has a title, version, and artist. In the db the artist is registered with all the titles to his/her repertoire. When matching playlists, reported by many societies, the titles are often misspelled, contain the artist and version sometimes, other times they're separated into three distinct fields, etc... therefore, i find myself having to do tons of preprocessing via a complex stored procedure (MS-SQL) before outputting something trimmed down to a manageable size. Once this is done, i pass it all through rapidfuzz by scoring the title, version and artist separately with differing methods and weights applied (basic multiply by a coeff) then add and average them to give me a final score. To date, this works exceptionally well, however, i often deal with exceedingly larger and larger playlists and need to shave milliseconds per iteration or process the whole list in one shot.

this is where i'm at, not sure if it helps but I spent several hours playing around with differing combos


string lengths vary from 3 to over 20, e.g. "Flute Quartet No. 2 in G major, K. 285a - II. Temp"

**Comment by maxbachmann** [comment]
There are still a couple of things that can be done to increase the performance of RapidFuzz especially when searching through a list like in extract or a multi match function as discussed here:

1) for use cases like yours the library would require a way to specify custom functions for extract, that are called in an optimized way and not through Python as discussed in #72. There are generally two ways to approach this:
    1) add a way to specify custom functions implemented in C, that are directly called. Similar to the way this is done e.g. in sqlite.
        \+ when implemented correctly by the user this will probably be very fast
         \- has to be compiled
         \- requires more effort from the user and he has to know how to write this implementation efficiently
     2) let the user specify his implementation e.g. in form of a dict -> compile this dict to a optimized C structure through a `compile` function of RapidFuzz -> use this optimized C structure as string metric
         \+ a lot simpler to use
         \- a lot harder to implement inside RapidFuzz. I would need to find a way to convert the Python dict to a efficient implementation, that is stored in some kind of C structure and implement a generic function for this use case, that can evaluate them in an efficient way.
        \+- can never be as fast as fast as 1), but probably most people would use 1) incorrectly, so for them it might be faster
2) add a multiprocess module to calculate multiple distances in parallel. This would require me to release the global interpreter Lock in Python, so it would only work for distance metrics and preprocessors provided by RapidFuzz, since calling a Python function requires the GIL to be acquired.
3) For short strings <64 it is possible to calculate the Levenshtein distance for multiple strings at the same time (e.g. 8 8 character strings), which could make a multi match function a lot faster.
4) Add SIMD implementation, which could use e.g. 128 bit values. This would speed up the Levenshtein calculation for longer strings. For shorter strings even more strings could be encoded using 3). However since not all CPUs support those operations it would have to check the CPU features at runtime to select the correct implementation

Btw as a side note I am absolutely no specialist on this topic either. I started this project last spring without having a clue about string matching simply because most other libraries are GPL licensed, slow or both :joy: The string matching methods of RapidFuzz are currently all from FuzzyWuzzy, or well known ones like Levenshtein or Hamming.

**Comment by zeek-ja** [comment]
I'll keep tweaking what i have so far and see what you come up with in subsequent releases ;) 

good luck and let me know if there's anything i can do to help test if you need.

**Comment by fletcheaston** [comment]
I've got a similar use case, I'm matching a large list of strings (>50k strings) against itself, and trying to get an N x N matrix of similarity scores. Right now, I'm using a helper function like this...

```
def compare(strings: list[str], limit: int = 100, min_score: int = 0) -> np.ndarray:
    shape = (
        len(strings),
        len(strings),
    )
    comparisons = np.zeros(shape, dtype=np.int8)

    for x_index, x_string in enumerate(strings):
        other_strings = strings[x_index + 1 :]
        extractions = process.extract(
            query=x_string,
            choices=other_strings,
            scorer=fuzz.ratio,
            limit=limit,
            score_cutoff=min_score,
        )
        for y_string, score, y_index in extractions:
            comparisons[x_index][y_index] = score
            comparisons[y_index][x_index] = score

    return comparisons
```

Which takes ~175 seconds for a list of 65k strings. I assume the vast majority of time is spent going from Python to C++ and back, as opposed to the actual matching. I'd be happy to help contribute if possible :)

**Comment by maxbachmann** [comment]
> I'd be happy to help contribute if possible :)

This would be awesome :)
You can find the current implementation of the process module here: https://github.com/maxbachmann/RapidFuzz/blob/main/src/cpp_process.pyx

A couple of comments towards the implementation:
- As a difference to extract/extractOne, this new function should only accept two iterables and does not require any special handling for dictionaries.
- I think at least for the start it would be enough to support only scorers/processors, which are part of RapidFuzz. Different functions would have to be called through python, so for them this would not be much faster anyways.
- The function should allow the use of two different lists. However special handling for two similar lists in the way you suggested above would be nice. (This can be detected using `list1 is list2`, which check whether they point to the same PyObject*)
- Depending on the scorer the function requires different return types:
  - for distances ndarray of a big integer type
  - for similarities ndarray of double
- The implementation should use the numpy c api. This is very simple with cython, since it will generate the code for you: https://cython.readthedocs.io/en/latest/src/tutorial/numpy.html. Note, that this is only required for the performance critical parts like writing into the array. It is completely fine to call e.g. the np.zeros function through python when allocating the array, since it is not really relevant for performance. AFAIK this should only require you to tell cython the shape of the array using cdef and then access the elements using `[x, y]` instead of `[x][y]` (btw this is faster in Python as well)

When you need further explanations of the code, or run into different problems, feel free to ask for help ;)

**Comment by NikhilKothari** [comment]
Hey @maxbachmann! Firstly, RapidFuzz is insane! :)

I have a similar use case where I'm trying to match a list of strings to another list of strings. So for now, should I use the process.extract function with one for loop? (like the code below)

```
for query in list1:
    process.extract(query, list2, scorer=fuzz.partial_ratio, limit=100, processor=None)
```

Also, the extract function returns a sorted array. Is it possible to make that thing optional? I'm working on a real time use case where I need to preserve the order, add some another score in the RapidFuzz's score and then sort in the end. If there's a work around for this, it would help immensely.

**Comment by maxbachmann** [comment]
> Firstly, RapidFuzz is insane! :)

Glad you like it :)

> process.extract(query, list2, scorer=fuzz.partial_ratio, limit=100, processor=None)

Note that in case you actually want all elements you should use `limit=None`

> Also, the extract function returns a sorted array. Is it possible to make that thing optional?

So far this is not possible. When returning all elements using `limit=None` the sorting of the results + the creation of the result list takes more time than the actual string matching. So right now you can probably simply iterate over both lists and store each score.

I am currently working on the cdist implementation myself and it will be included in the next release.

**Comment by NikhilKothari** [comment]
Got it. For the time being, I'm using ```process.extract_iter```. It seems to give a generator object without sorting. 
When do you estimate the next release with the cdist implementation? Need it desperately!

>Note that in case you actually want all elements you should use ```limit=None```

This helped.

**Comment by maxbachmann** [comment]
> When do you estimate the next release with the cdist implementation?

I am really not sure about this yet.

**Comment by maxbachmann** [comment]
I did just release version 1.6.0 which does include cdist:
```python
>>> from rapidfuzz import process, fuzz
>>> strings=["abcd", "bcde", "cdef", "abcd"]
>>> process.cdist(strings, strings, scorer=fuzz.ratio)
array([[100,  75,  50, 100],
       [ 75, 100,  75,  75],
       [ 50,  75, 100,  50],
       [100,  75,  50, 100]], dtype=uint8)
```
