### ISSUE TITLE
Feature Suggestion: Select specific scorers for WRatio

### ISSUE THREAD

**Issue by dylanlevine** [rapidfuzz/RapidFuzz#72]
Given that certain types of scorers are most useful in certain situations, I thought it would be interesting for WRatio to have a way to select only certain scorer functions for weighting.

**Comment by maxbachmann** [comment]
## Current Options
Right now you can already achieve this behavior by implementing a custom scorer:
```python
def my_scorer(a, b, processor, score_cutoff):
  similarity = fuzz.ratio(a, b, processor, score_cutoff)
  score_cutoff = max(similarity, score_cutoff)
  similarity = max(similarity, fuzz.partial_ratio(a, b, processor, score_cutoff) * 0.8)
  return similarity

process.extract(query, choices, scorer=my_scorer)
```

However this approach has the disadvantage, that it has to call the scorer through Python which can be slow.

## Planned implementation

In my opinion `WRatio` should keep the current behavior, since it is a copy of the behavior of FuzzyWuzzy and is not really straight forward (e.g. for different length differences it chooses different scorers with different weights).


I already planned a `**kwargs` argument for process.extract/extractOne/extract_iter, that is passed to the scorer which allows e.g.
```python
process.extract(query, choices, scorer=string_metric.normalized_levenshtein, weights=(1,1,2))
```
in a similar way a object describing the matching algorithm could be passed

## Open questions

The main question that's still open is the format in which the scoring algorithm should be described
A very simple concept would be
```python
scorer_dict = {
  fuzz.ratio: 1,
  fuzz.partial_ratio: 0.8
}
```
which describes which algorithms should be used and how the results of these scorers should be weighted. There could be different generic scorers that e.g. return the max similarity of all algorithms or the sum. However some more advanced things a user might want to describe are:
- a length ratio range in which a specific algorithm is used with a specific weight (similar to WRatio, which uses different ratios and weights for different length ratios)
- more advanced ways to combine algorithms -> max(sum(ratio1, ratio2), ratio3)
- different kwargs to pass to different scorers -> max(ratio1(**kwargs1), ratio2(**kwargs2))

With a more advanced format e.g. WRatio could be described in the following way:
```python
algorithm = {
    'type': 'max',
     'algorithms': [
       {'type': 'scorer', 'scorer': fuzz.ratio},
       {
         'type': 'scorer',
         'length_ratio': { 'max': 1.5 },
         'weight': 0.95,
         'scorer': fuzz.token_ratio
       },
       {
          'type': 'max',
          'length_ratio': { 'min': 1.5, 'max': 8 },
          'weight': 0.9,
          'algorithms': [
            {'type': 'scorer', 'scorer': fuzz.partial_ratio},
            {
              'type': 'scorer',
              'weight': 0.95,
              'scorer': fuzz.partial_token_ratio
            },
          ]
       },
       {
          'type': 'max',
          'length_ratio': { 'min': 8 },
          'weight': 0.6,
          'algorithms': [
            {'type': 'scorer', 'scorer': fuzz.partial_ratio},
            {
              'type': 'scorer',
              'weight': 0.95,
              'scorer': fuzz.partial_token_ratio
            },
          ]
       }
     ]
 }
```

I am open for input on this format. Important parts are:
- should be simple and logical for the user to create
- should be extensible in the future without breaking code written for previous versions of the library
- does not has to cover all use cases, since as shown above it is pretty simple to implement a scorer in Python (it is just slower)
  -> e.g. it would be fine when scorers have to be scorers provided by rapidfuzz and no custom Python functions, since calling custom Python functions is slow anyways

**Comment by maxbachmann** [comment]
I decided that this is out of scope for the project. However I will add a C-Api to specify custom scorers in v2.0 (see https://github.com/maxbachmann/RapidFuzz/issues/156), which can be used to implement different scorer functions in any language which allows the usage of a C-API (e.g. C/C++/Cython or Rust)
