### ISSUE TITLE
[Questions]: Weighting characters to handle acronyms / fixed numbers

### ISSUE THREAD

**Issue by Dan-Treacher** [rapidfuzz/RapidFuzz#74]
Hi - thanks for all your work on this library, it works very nicely.

I have a question about applying weights to certain characters in order to cater for things like acronyms and numbers that should remain the same:

For example, if I had a test string `Guide V16 LDV` and an array of strings which included the 'true' version: `Guide V16 Laker Deep V`, I might want to upweight the capital letters and numerical characters in the test string (I don't want the numbers to change) so that a match to `Guide V16 Laker Deep V` is more likely than a match to `Guide V18 SD` for example.

I have noticed that `token_set_ratio` gives more accurate results than `token_sort_ratio` when acronyms are involved, but when the 'true' version is longer than the test string, the 100% match from token_set_ratio causes it to match to the wrong thing: There are instances where `Guide V16 LDV` should match to `Guide V16 Laker Deep V` and not `Guide V16 Laker Deep V Hidden Pro` for example

For context, I'm dealing with a large dataset consisting of product makes & models entered by users. I also have a list of 'ground truth' make & models provided by the product manufacturers. My goal is to try and match up the user entered models with the manufacturer's model name. Is the inclusion of a custom weighting complex, or is it incorporated in some other method I've overlooked?

**Comment by maxbachmann** [comment]
So far, this is not possible. All scorers in fuzz.* use the Levenshtein distance with the following weights:
- substitution = 2
- insertion = 1
- deletion = 1
and normalize the edit distance using `100 - 100 * edit_dist / (len1 + len2)`

There is also `rapidfuzz.string_metric.levenshtein`, which accepts custom weights for substitution/insertion/deletion. However, only the normal Levenshtein distance and the weighted Levenshtein distance used in `fuzz.*` have very optimised implementations. I calculate the Levenshtein distance for all other weights using Wagner Fischer, which is slower. 
It would be possible to add custom weights on a character basis similar to the implementation here: https://github.com/infoscout/weighted-levenshtein/blob/ff739559d0a8ca52a21ff9cac29e361ddb7d86d5/weighted_levenshtein/clev.pyx#L425
However, to support the whole Unicode range, this would require hashmaps, which would most likely make it relatively slow. I implemented a very quick proof of concept which took around 20 times as long as the current generic implementation, which is already slower than the bitparallel implementation.

**Comment by Dan-Treacher** [comment]
I see, thanks for the detailed explanation.

For my specific application I have many hundreds of thousands of strings to check so an unoptimised approach would probably be far too slow. I'll have to look into alternate string clustering methods instead.

Thanks again

**Comment by maxbachmann** [comment]
I looked into it a bit more yesterday evening and at least in C++ was able to get it down to around 4x of the bitparallel implementation or 1.5x the runtime of the current generic implementation.
For extended ascii strings it would be possible to store the mapping in 3 arrays:
- delete/insert is a 256 element array
- substitution is a 256*256 matrix
In my test this took 1.1 times as long as the current generic implementation / 3.1x the bitparallel implementation
As a important note, this is benchmarked directly in C++, so the integration with Python still has a couple of unknown factors:
- when calling a single function argument parsing takes a considerate amount of time
  -> The runtime difference might not be as big
  -> depending on the way the arguments are passed numpy array / dict this might introduce new overhead to get elements from the dict vs a hashmap optimised for the element types I am using. Numpy arrays would probably be relatively cheap, since they should allow me direct access to their memory
- when calling through process.* a big part of the performance improvement of fuzz.ratio is achieved by precalculating a bitvector of the query (about 2x improvement) which can not be done for the generic implementation

So I guess it should be possible to achieve something around 10x the runtime of fuzz.ratio. However e.g. fuzz.token_set_ratio is a lot slower than fuzz.ratio as well, so this might not be so bad.

Todos:
- How to pass the mapping
  - I guess numpy arrays would be performant and could be used
  - additionally dicts should probably be accepted especially for substitutions, since 0x10FFFF ^ 2 Bytes is definetly to much to fit into memory
- process.* needs to accept additional kwargs so no calls to a python function are required when matching whole lists
