### ISSUE TITLE
Add support to release aarch64 wheels 

### ISSUE THREAD

**Issue by odidev** [rapidfuzz/RapidFuzz#82]
Problem
---------
On aarch64, pip install RapidFuzz builds the wheels from source code and then install it. It requires user to have development environment installed on his system. also, it take some time to build the wheels than downloading and extracting the wheels from pypi.

Resolution
-----------
On aarch64, pip install RapidFuzz should download the wheels from pypi

@maxbachmann , please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by maxbachmann** [comment]
Adding support for aarch64 sounds good to me. The reason I did not add support so far is the missing support by GitHub Actions. Since Azure Pipelines added support for Aarch64/ARM64 last year, I was waiting for GitHub actions to add support for it as well.
In case you're willing to implement it, I would be fine with a Travis CI job for platforms that are not supported by GitHub Actions.

**Comment by odidev** [comment]
Hi @maxbachmann , thank you for your response. We can use qemu for adding aarch64 wheels support in GHA. Please let me know your view on this.

**Comment by maxbachmann** [comment]
As long as it works I am absolutely fine with this. In fact I would prefer having everything in GHA over a second CI solution.
