### ISSUE TITLE
Partial_ratio behaving unexpectedly

### ISSUE THREAD

**Issue by colestiegler** [rapidfuzz/RapidFuzz#90]
Hi, using the below code I would expect score1 to be at least as large as score2 since str1 contains str2, but it is less. I suspect it has something to do with the identification of best string subset, as removing the "c" in str1 resolves this unexpected behavior.  I'm using v1.2.1. Thanks!

```from rapidfuzz import fuzz, process
str1 = "a b a c b"
str2 = "a b "
match_value = "ax b"
score1 = fuzz.partial_ratio(str1, match_value)
score2 = fuzz.partial_ratio(str2, match_value)
print(f"str1 contains str2: {str2 in str1}")
print(f"Why is score1 ({score1:.2f}) < score2 ({score2:.2f})?")```

str1 contains str2: True
Why is score1 (50.00) < score2 (75.00)?

**Comment by maxbachmann** [comment]
Yes this is definitely a bug. It should have a score of 75 as well. An as you suspected it is a bug in the identification of the best substring. I will have to look into this more to see how this can be fixed. The whole partial_ratio still needs a lot of work to make it correct in all cases and faster (the current implementation is already a fallback for the faster implementation which had a bug).

**Comment by maxbachmann** [comment]
I fixed this specific issue in release [v.1.3.1](https://github.com/maxbachmann/RapidFuzz/releases/tag/v1.3.1).  However it still does not use the optimal alignment is some edge cases, since similar to FuzzyWuzzy it uses the longest common substrings as starting points of the optimal alignment. However this is not necessarily correct. I am still searching for a way to calculate this correct even for those edge cases, without losing to much performance.
