### ISSUE TITLE
Apply the RapidFuzz in Deduping DataFrame Pandas

### ISSUE THREAD

**Issue by bigredbug47** [rapidfuzz/RapidFuzz#91]
Hi @maxbachmann,

Thanks for your awesome library. But could you provide me the example how to apply RapidFuzz in the single DataFrame pandas (or from multiple df pandas).
I want to find which records are matching with other based on some specific columns.

Example:
```
DF1:                                                                                     
id       name     value                                                            
001      John      10                                                               
002      Anna      15                                                                
003      Lee       16                                                             

DF2:
id       name     value
004      Johnny    16  
006      Ana       15 
008      Joh       0  
```

So the return df should be following:
```
DF Matched:
id_left    name_left     id _right     name_right     matching_score
  001          John         004           Johnny          0.98
  002          Anna         006           Ana             0.82
  001          John         008           Joh             0.58
```

So could I solve the problem with the RapidFuzz? Or could you advise me how to solve them with the custom function 

Thank you.

**Comment by maxbachmann** [comment]
I would use `process.extractOne` for this task. Here is some pseudo code to show the usage. In the example I use fuzz.ratio since it is the fastest ratio (replace it with whichever ratio your using) and disable preprocessing (lowercasing + removal of non alphanumeric characters). In case you would like to preprocess the strings it would make sense to do so in front of the loop, so the same string is not preprocessed multiple times.
```python
// create dataframe with len(df1) for results
for name_left in df1["name"]:
    choice, score, index = process.extractOne(name_left, df2["name", scorer=fuzz.ratio, processor=None)
    // set the corresponding result in the result dataframe
```
